### ISSUE TITLE
Do you have any references about this project？

### ISSUE THREAD

**Issue by MDKusester** [dida1012/Edublocks_ESP32#20]
I am trying to use this project to build my own edublock project. I feel it is very difficult to understand the file structure of the project. Do you have any information to refer to and help me understand the role of each file in this project？
Thank you very much.

**Comment by dida1012** [comment]
Hello, MDKusester,

this project actually was build from to other Repos. Folders contain the project as follows:

esp32-micropython--> https://github.com/PrestonHackspace/esp32-micropython
edublocks-micropython--> https://github.com/AllAboutCode/edublocks-micropython

I bascially then just edited the files in Edublocks_ESP32/edublocks-micropython/src/blocks/ to create my own edublocks which  I used in my project. You can find blocks which utilize the RFID library (https://github.com/wendlers/micropython-mfrc522) to read/write RFID Tags through edublocks.
